<a href="https://colab.research.google.com/github/westlfower/pythone/blob/main/1219%EB%B0%A9%EA%B3%BC%ED%9B%84numpy1%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=[[[1,2,3],[4,5,6]],[[7,8,9],[10,12]]]

In [3]:
a

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 12]]]

In [4]:
import numpy as np

# The original code 'a[[1:2],[0:1],[:]]' caused a 'SyntaxError'.
# This is because standard Python lists do not support multi-dimensional
# indexing using multiple bracket sets. This syntax is specific to NumPy arrays,
# where slices for different dimensions are separated by commas within a
# single set of brackets.

# Diagnosis for the variable 'a':
# Your list 'a' (`[[[1,2,3],[4,5,6]],[[7,8,9],[10,12]]]`) has an irregular shape.
# Specifically, the sublist `[10,12]` has 2 elements, while `[7,8,9]` has 3.
# If you convert such an irregular list directly to a NumPy array using `np.array(a)`,
# it will create a 1-dimensional array of `dtype=object` (where each element is a list),
# not a uniformly shaped multi-dimensional numerical array. This means that
# applying multi-dimensional slicing like `[slice1, slice2, slice3]` to it
# would still lead to an `IndexError` (too many indices) as it's fundamentally a 1D array of objects.

# Fix for the SyntaxError and demonstration of correct NumPy slicing:
# To use multi-dimensional slicing as implied by the original code,
# you would need a uniformly shaped NumPy array.
# Let's create a uniformly shaped example for demonstration:
uniform_np_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# Now, applying the correct NumPy multi-dimensional slicing syntax:
sliced_result = uniform_np_array[1:2, 0:1, :]
print(f"Result from a uniformly shaped NumPy array using correct slicing: {sliced_result}")

# If you intended to access elements from your original Python list 'a' (which is irregular),
# you would typically use chained indexing:
# For example, to access the element `[7,8,9]` (which is `a[1][0]`):
print(f"Accessing a[1][0] from your original list 'a': {a[1][0]}")
# For example, to access the element `[10,12]` (which is `a[1][1]`):
print(f"Accessing a[1][1] from your original list 'a': {a[1][1]}")

SyntaxError: invalid syntax (ipython-input-3709392625.py, line 1)

In [7]:
a[0][1][1:3]

[5, 6]

In [6]:
a

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 12]]]

In [8]:
a=np.arange(15).reshape(3,5)

In [9]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
a.shape

(3, 5)

In [11]:
a.ndim

2

In [12]:
a.itemsize

8

In [13]:
a.size

15

In [14]:
b=np.array([6,7,8])

In [15]:
b

array([6, 7, 8])

In [17]:
b.ndim

1

In [18]:
b.size

3

In [19]:
b.shape

(3,)

In [20]:
b.reshape(1,3)

array([[6, 7, 8]])

In [24]:
a=np.array([[[1,3,2],[2,4,5]],[[1,3,2],[2,4,5]]])

In [25]:
a.shape

(2, 2, 3)